PolynomialFeatures:
  poly_degree: 2

KBinsDiscretizer:
  kbins_n_bins: 5

SplineTransformer:
  spline_degree: 3
  spline_knots: 3

AutoFeat:
  feateng_steps: 2
  max_gb: 2
  transformations:
    - '1/'
    - 'log'
    - 'abs'
    - 'sqrt'
  n_jobs: 1